version: '3.1'

services:
  hepsub-cgrates:
    container_name: hepsub-cgrates
    image: sipcapture/hepsub-cgrates
    restart: always
    environment:
      - PUBLIC_IP=${PUBLIC_IP:-voipmonitor-hep}
      - PUBLIC_PORT=${PUBLIC_PORT:-18088}
      - HOMER_IP=${HOMER_IP:-homer-webapp}
      - HOMER_PORT=${HOMER_PORT:-9080}
      - API_URL=${HOMER_IP:-http://cgrates:8202}
    ports:
      - "18088:18088/tcp"

